#!/usr/bin/env python

import sys
sys.path.extend(["/home/hpc/bca1/bca109/bin/GeneralMDTools", "/home/t/Source/GeneralMDTools"])

import os
import automationtools as at

os.environ["STEP_CONFIG"] = "conf"
os.environ["STEP_GROUP"] = "S17"

group = ""
configfile = ""
group, configfile, cp = at.argsinit()

at.check_and_move(cp.get(group, "move").split(), group)
at.check_and_copy(cp.get(group, "copy").split(), group)

at.mangle_config(configfile, group)

if cp.has_option(group, "field_file"):
    os.system("cp " + cp.get(group, "field_file") + " FIELD")

at.pbs_runner(configfile, group)
if cp.has_option(group, "condition"):
    if at.condition(cp.get(group, "condition")):
        print "cond+"
        exit()
    else:
        print "cond-"

os.system("cd $PBS_O_WORKDIR; " + cp.get(group, "executable"))
