#!/bin/bash -lx

module load intelmpi
module load intel64
cd ${PBS_O_WORKDIR}

qsub -l nodes=2:ppn=40,walltime=3:00:00 -N step1c -W depend=afterany:${PBS_JOBID} /home/hpc/bca1/bca109/bin/GeneralMDTools/Step1c

mpirun_rrze -npernode 20 -pinexpr N:0-19 ${HOME}/dlpc19emmy-intelmpi-ifort/execute/DLPOLY.X
