#!/usr/bin/env python

import sys
sys.path.extend(["/home/hpc/bca1/bca109/bin/GeneralMDTools", "/home/t/Source/GeneralMDTools"])

#Check if add cluster has docked onto the center cluster

#import AtomEnsemble as ae

import os
import automationtools as at

group = ""
configfile = ""
group, configfile, cp = at.argsinit()

at.check_and_move(cp.get(group, "move").split(), group)
at.check_and_copy(cp.get(group, "copy").split(), group)

print os.getcwd()

#import sys
import fieldtools as ft
import iotools as iot
import random
#import numpy as np

def frand(minval=0.0, maxval=1.0):
    return random.uniform(minval, maxval)

#seed random
random.seed()

#Get index
#index = int(sys.argv[1])

print os.getcwd()

#Load last frame
last_frame = iot.DLP2HReader(fileobj="HISTORY")[-1]
solvate_hull = iot.DLP2HReader(fileobj="SolvateHull")[0]
len_last_frame = len(last_frame['element'])
last_frame.center()

try:
    del last_frame['velocity']
except KeyError:
    pass

try:
    del last_frame['force']
except KeyError:
    pass

try:
    del solvate_hull['velocity']
except KeyError:
    pass

try:
    del solvate_hull['force']
except KeyError:
    pass

#solvate_hull.center()
last_frame.intersect_molecules(solvate_hull, 3.5, 4)

#construct field file
ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if index < len_last_frame:
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI_fixed")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI_fixed")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH_fixed")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3_fixed")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO_fixed")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O_fixed")
    else:
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O")

field_out = open("FIELD", "w")
field_out.write(str(ff))
field_out.close()

os.system("cp FIELD FIELD_clusterfix")

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI_fixed")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O")

field_out = open("FIELD_BIfix", "w")
field_out.write(str(ff))
field_out.close()

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI_fixed")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI_fixed")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH_fixed")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O_fixed")

field_out = open("FIELD_BIOIOHOWfix", "w")
field_out.write(str(ff))
field_out.close()

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI_fixed")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH_fixed")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O_fixed")

field_out = open("FIELD_OIOHOWfix", "w")
field_out.write(str(ff))
field_out.close()

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI_fixed")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH_fixed")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3_fixed")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO_fixed")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O_fixed")

field_out = open("FIELD_OIOHOWNO3DMSOfix", "w")
field_out.write(str(ff))
field_out.close()

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI_fixed")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO_fixed")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O")

field_out = open("FIELD_BIDMSOfix", "w")
field_out.write(str(ff))
field_out.close()

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO_fixed")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O")

field_out = open("FIELD_DMSOfix", "w")
field_out.write(str(ff))
field_out.close()

ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
for index, atom in enumerate(last_frame['element']):
    if atom == "BI":
        ff.append_molecule("FIELD_Mol_BI")
    elif atom == "OI":
        ff.append_molecule("FIELD_Mol_OI")
    elif atom == "OH":
        ff.append_molecule("FIELD_Mol_OH")
    elif atom == "NN":
        ff.append_molecule("FIELD_Mol_NO3")
    elif atom == "SD":
        ff.append_molecule("FIELD_Mol_DMSO")
    elif atom == "OW":
        ff.append_molecule("FIELD_Mol_H2O")

field_out = open("FIELD_free", "w")
field_out.write(str(ff))
field_out.close()

last_frame.boxvector = solvate_hull.boxvector

conf_writer = iot.DLP2CWriter(fileobj="CONFIG", overwrite=True)
conf_writer.write(last_frame)
del conf_writer

at.pbs_runner(configfile, group)

# start 4
