#!/usr/bin/env python

import sys
sys.path.extend(["/home/hpc/bca1/bca109/bin/GeneralMDTools", "/home/t/Source/GeneralMDTools"])

#Check if add cluster has docked onto the center cluster

#import AtomEnsemble as ae

import os
import automationtools as at
if 'PBS_O_WORKDIR' in os.environ:
    os.chdir(os.environ['PBS_O_WORKDIR'])

#import sys
import fieldtools as ft
import iotools as iot
import random
#import numpy as np

def frand(minval=0.0, maxval=1.0):
    return random.uniform(minval, maxval)

#seed random
random.seed()

at.check_and_write_error(["HISTORY", "CONTROL3", "CONTROL3R"], postfix="step3_pre")
at.check_and_move(["OUTPUT", "STATIS", "REVIVE"], "step2")

#Get index
#index = int(sys.argv[1])

#Load last frame
last_frame = iot.DLP2HReader(fileobj="HISTORY")[-1]

# check if aggregation has occurred. If yes solvate, if not rinse and repeat
print "LFD" + str(last_frame.get_chains(dist=3.5))
if last_frame.get_chains(dist=3.5) != 1:
    at.check_and_move(["HISTORY"], "step2")
    at.check_and_copy(["REVCON"])
    os.system("mv REVCON CONFIG")
    # start step2
    os.system('cp CONTROL1R CONTROL; qsub -l nodes=2:ppn=40,walltime=2:00:00  -N step2 -W depend=afterany:'+ os.environ['PBS_JOBID'] + ' /home/hpc/bca1/bca109/bin/GeneralMDTools/Step2')
else:
    solvate_hull = iot.DLP2HReader(fileobj="SolvateHull")[0]
    len_last_frame = len(last_frame['element'])
    last_frame.center()

    try:
        del last_frame['velocity']
    except KeyError:
        pass

    try:
        del last_frame['force']
    except KeyError:
        pass

    try:
        del solvate_hull['velocity']
    except KeyError:
        pass

    try:
        del solvate_hull['force']
    except KeyError:
        pass

    #solvate_hull.center()
    last_frame.intersect_molecules(solvate_hull, 3.5, 4)

    #construct field file
    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if index < len_last_frame:
            if atom == "BI":
                ff.append_molecule("FIELD_Mol_BI_fixed")
            elif atom == "OI":
                ff.append_molecule("FIELD_Mol_OI_fixed")
            elif atom == "OH":
                ff.append_molecule("FIELD_Mol_OH_fixed")
            elif atom == "NN":
                ff.append_molecule("FIELD_Mol_NO3_fixed")
            elif atom == "SD":
                ff.append_molecule("FIELD_Mol_DMSO_fixed")
            elif atom == "OW":
                ff.append_molecule("FIELD_Mol_H2O_fixed")
        else:
            if atom == "BI":
                ff.append_molecule("FIELD_Mol_BI")
            elif atom == "OI":
                ff.append_molecule("FIELD_Mol_OI")
            elif atom == "OH":
                ff.append_molecule("FIELD_Mol_OH")
            elif atom == "NN":
                ff.append_molecule("FIELD_Mol_NO3")
            elif atom == "SD":
                ff.append_molecule("FIELD_Mol_DMSO")
            elif atom == "OW":
                ff.append_molecule("FIELD_Mol_H2O")

    field_out = open("FIELD", "w")
    field_out.write(str(ff))
    field_out.close()

    os.system("cp FIELD FIELD_clusterfix")

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI_fixed")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O")

    field_out = open("FIELD_BIfix", "w")
    field_out.write(str(ff))
    field_out.close()

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI_fixed")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI_fixed")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH_fixed")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O_fixed")

    field_out = open("FIELD_BIOIOHOWfix", "w")
    field_out.write(str(ff))
    field_out.close()

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI_fixed")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH_fixed")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O_fixed")

    field_out = open("FIELD_OIOHOWfix", "w")
    field_out.write(str(ff))
    field_out.close()

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI_fixed")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH_fixed")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3_fixed")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO_fixed")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O_fixed")

    field_out = open("FIELD_OIOHOWNO3DMSOfix", "w")
    field_out.write(str(ff))
    field_out.close()

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI_fixed")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO_fixed")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O")

    field_out = open("FIELD_BIDMSOfix", "w")
    field_out.write(str(ff))
    field_out.close()

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO_fixed")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O")

    field_out = open("FIELD_DMSOfix", "w")
    field_out.write(str(ff))
    field_out.close()

    ff = ft.FieldCollection(input_file="FIELD_vdw_plus")
    for index, atom in enumerate(last_frame['element']):
        if atom == "BI":
            ff.append_molecule("FIELD_Mol_BI")
        elif atom == "OI":
            ff.append_molecule("FIELD_Mol_OI")
        elif atom == "OH":
            ff.append_molecule("FIELD_Mol_OH")
        elif atom == "NN":
            ff.append_molecule("FIELD_Mol_NO3")
        elif atom == "SD":
            ff.append_molecule("FIELD_Mol_DMSO")
        elif atom == "OW":
            ff.append_molecule("FIELD_Mol_H2O")

    field_out = open("FIELD_free", "w")
    field_out.write(str(ff))
    field_out.close()

    last_frame.boxvector = solvate_hull.boxvector

    conf_writer = iot.DLP2CWriter(fileobj="CONFIG", overwrite=True)
    conf_writer.write(last_frame)
    del conf_writer

    at.check_and_move(["HISTORY"], "step2")
    at.check_and_copy(["CONFIG", "FIELD"], "step3")
    os.system('cp CONTROL3 CONTROL; qsub -l nodes=5:ppn=40,walltime=2:00:00 -N step4 -W depend=afterany:'+ os.environ['PBS_JOBID'] + ' /home/hpc/bca1/bca109/bin/GeneralMDTools/Step4')
    # start 4
