#!/usr/bin/env python

import sys
sys.path.extend(["/home/hpc/bca1/bca109/bin/GeneralMDTools", "/home/t/Source/GeneralMDTools"])

import os
import automationtools as at
import ConfigParser

if 'PBS_O_WORKDIR' in os.environ:
    os.chdir(os.environ['PBS_O_WORKDIR'])

if 'STEP_GROUP' in os.environ:
    group = os.environ['STEP_GROUP']
else:
    group = sys.argv[2]

if 'STEP_CONFIG' in os.environ:
    configfile = os.environ['STEP_CONFIG']
else:
    configfile = sys.argv[1]

cp = ConfigParser.GlobalConfigParser()
cp.read(configfile)

at.mangle_config(configfile, group)

at.pbs_runner(configfile, group)

os.system("cd $PBS_O_WORKDIR; " + cp.get(group, "executable"))
