#!/bin/bash -lx

module load intelmpi
module load intel64
cd ${PBS_O_WORKDIR}

qsub -l nodes=2:ppn=40,walltime=0:30:00 -q work -N step5 -W depend=afterok:${PBS_JOBID} ./Step5
qsub -l nodes=2:ppn=40,walltime=0:30:00 -q work -N step4b -W depend=afternotok:${PBS_JOBID} ./Step4b
mpirun_rrze -npernode 20 -pinexpr N:0-19 ${HOME}/dlpc19emmy-intelmpi-ifort/execute/DLPOLY.X


# step 5
